### ISSUE TITLE
Duplicate thingCategory Apparel: Royal Armor, Ancient Mail

### ISSUE THREAD

**Issue by Trisscar05** [TorannD/TMagic#9]
Currently doing rebuilding of modlist for bugtesting purposes, Royal Armor and Ancient Mail have had this issue for a while, thought I should make a note of it:
https://gist.github.com/HugsLibRecordKeeper/2dcf64f7742c9d71bdb63dfcf5ef1325

**Comment by notfood** [comment]
This line: 
https://github.com/TorannD/TMagic/blob/master/Defs/ThingDefs/TM_Apparel.xml#L65

Allows other mods to hijack the base and change it, in my case some other mod was introducing another `<thingCategories><li>Apparel</li></thingCategories>`

It's probably an oversight, the fix is to change `ApparelBase` to `TM_ApparelBase`
